### ISSUE TITLE
TensorFlow version?

### ISSUE THREAD

**Issue by Breta01** [tportenier/gramgan#1]
Hi,

your results look really good!
I would like to try running your code. Right now I can't figure out version of TensorFlow you were using. Can you please provide requirements with exact version of tensorflow?
Also I think adding requirements.txt to repository could help future users.
(So far I tried TF 2+, 1.15, 1.24 each giving different error)

Thank you

**Comment by tportenier** [comment]
Hi,

We tested Tensorflow 1.15 and 2.2.

**Comment by Breta01** [comment]
Ok, I will try it later today and see how it goes.

**Comment by Breta01** [comment]
I figured that out and it works now. I am using TensorFlow 1.15 and Python 3.7. I just had to change following line:
https://github.com/tportenier/gramgan/blob/45508eec4cf9a5c515ac6c70e52cc70dae96c171/train_single.py#L61
to
```python
reduction_indices=list(range(1, x.shape.ndims))))
```
I guess it is due to the different implementation of `range()` in Python 3 and 2. It might be worth changing it in the repo.
